// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  CommentCommand = 2,
  Braced = 3,
  BraceContent = 4,
  PreambleCommand = 5,
  Quoted = 6,
  Number = 7,
  Identifier = 8,
  StringCommand = 9,
  Command = 10,
  Key = 11,
  Comment = 12
