name: Checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: script -e -c "npm run test"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Biome Linter
        run: npm run check

  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Typescript check
        run: npx tsc --noEmit

  check-deployed-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Check NPM global install
        run: npx bibtex-tidy -v

  check-deployed-library:
    runs-on: ubuntu-latest
    steps:
      - name: Check NPM package works in node
        run: |
          mkdir ~/foobar
          cd ~/foobar
          npm install git+https://github.com/FlamingTempura/bibtex-tidy.git
          node -e "console.log(require('bibtex-tidy').tidy('test'))"
