name: Checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      # Seems to need to be first otherwise npx cannot find bibtex-tidy
      - name: Check NPM global install
        run: npx bibtex-tidy -v

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Typescript check
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Check NPM package works in node
        run: |
          mkdir ~/foobar
          cd ~/foobar
          npm install git+https://github.com/FlamingTempura/bibtex-tidy.git
          node -e "console.log(require('bibtex-tidy').tidy('test'))"
